### ISSUE TITLE
midi-node fails to start

### ISSUE THREAD

**Issue by bretth18** [nadav-dav/Ps3-Midi#1]
information from npm-debug.log
OSX 10.10.5

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart midi-node@0.0.0
7 info start midi-node@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info midi-node@0.0.0 Failed to exec start script
10 verbose stack Error: midi-node@0.0.0 start: `node .`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid midi-node@0.0.0
12 verbose cwd /Users/bretthenderson/Ps3-Midi/node_modules
13 error Darwin 14.5.0
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.2
16 error npm  v2.7.5
17 error code ELIFECYCLE
18 error midi-node@0.0.0 start: `node .`
18 error Exit status 1
19 error Failed at the midi-node@0.0.0 start script 'node .'.
19 error This is most likely a problem with the midi-node package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node .
19 error You can get their info via:
19 error     npm owner ls midi-node
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by bretth18** [comment]
just found out the midi-node is managed by jokr joel.krebs@gmail.com
My apologies
